### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by tbeason** [zachmatson/ArgMacros.jl#4]
Would be good to have at least one example in the docs where you actually USE these. I had to look elsewhere to see exactly how to use (ie, supply) the short flags, long flags, etc. My memory isn't what it used to be!

**Comment by zachmatson** [comment]
Thanks for adding an issue! What additional information do you think would have made the docs more useful for you? There is a section on using arguments but now that I look there is no use of flagged arguments there and it takes going into the individual docstrings to see an example. If the examples in the main docs page had flagged arguments would it solve this?

**Comment by tbeason** [comment]
Yea just something showing how to supply arguments. I know that is more about Julia and less about your package but it is definitely relevant and would be simple, eg

```
julia myscript.jl --foo "MyName"
```

**Comment by zachmatson** [comment]
Ohh ok I misunderstood what you meant before. Yeah that looks like a pretty glaring oversight, I will add some documentation about that soon.

**Comment by zachmatson** [comment]
Added relevant example in 6e61e57 so this issue will now be marked closed.
